apiVersion: apps/v1
kind: Deployment
metadata:
  name: termino-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: termino-backend
  template:
    metadata:
      labels:
        app: termino-backend
    spec:
      containers:
        - name: backend
          image: termino-backend:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: REDIS_URL
              value: "redis://redis:6379"
          ports:
            - containerPort: 3001
